print("1. Gather the dirty clothes.")
print("2. Sort the clothes by color.")
print("3. Put the clothes in the washing machine.")
print("4. Add detergent or a capsule.")
print("5. Select the washing program.")
print("6. Press the 'Start' button.")
print("7. Wait for the washing to finish.")
print("8. Take the clothes out of the machine.")
print("9. Hang the clothes to dry.")
